//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRv1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reminder", Namespace="http://schemas.datacontract.org/2004/07/Model_")]
    public partial class Reminder : SRv1.Entity
    {
        
        private string _cidField;
        
        private string _textField;
        
        private int _uidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _cid
        {
            get
            {
                return this._cidField;
            }
            set
            {
                this._cidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _text
        {
            get
            {
                return this._textField;
            }
            set
            {
                this._textField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _uid
        {
            get
            {
                return this._uidField;
            }
            set
            {
                this._uidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/Model_")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRv1.Event))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRv1.NoteItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRv1.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRv1.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRv1.Reminder))]
    public partial class Entity : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/Model_")]
    public partial class Event : SRv1.Entity
    {
        
        private int _IDField;
        
        private string _cidField;
        
        private string _dateField;
        
        private string _descriptionField;
        
        private string _nameField;
        
        private int _uidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ID
        {
            get
            {
                return this._IDField;
            }
            set
            {
                this._IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _cid
        {
            get
            {
                return this._cidField;
            }
            set
            {
                this._cidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _date
        {
            get
            {
                return this._dateField;
            }
            set
            {
                this._dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _description
        {
            get
            {
                return this._descriptionField;
            }
            set
            {
                this._descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _uid
        {
            get
            {
                return this._uidField;
            }
            set
            {
                this._uidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoteItem", Namespace="http://schemas.datacontract.org/2004/07/Model_")]
    public partial class NoteItem : SRv1.Entity
    {
        
        private string _cidField;
        
        private string _nameField;
        
        private string _textField;
        
        private int _uidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _cid
        {
            get
            {
                return this._cidField;
            }
            set
            {
                this._cidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name
        {
            get
            {
                return this._nameField;
            }
            set
            {
                this._nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _text
        {
            get
            {
                return this._textField;
            }
            set
            {
                this._textField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _uid
        {
            get
            {
                return this._uidField;
            }
            set
            {
                this._uidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model_")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRv1.Person))]
    public partial class User : SRv1.Entity
    {
        
        private int _absIdField;
        
        private string _pwdField;
        
        private int _typeField;
        
        private string _usrNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _absId
        {
            get
            {
                return this._absIdField;
            }
            set
            {
                this._absIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _pwd
        {
            get
            {
                return this._pwdField;
            }
            set
            {
                this._pwdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _type
        {
            get
            {
                return this._typeField;
            }
            set
            {
                this._typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _usrName
        {
            get
            {
                return this._usrNameField;
            }
            set
            {
                this._usrNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Model_")]
    public partial class Person : SRv1.User
    {
        
        private string _cidField;
        
        private string _fNameField;
        
        private string _lNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _cid
        {
            get
            {
                return this._cidField;
            }
            set
            {
                this._cidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _fName
        {
            get
            {
                return this._fNameField;
            }
            set
            {
                this._fNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _lName
        {
            get
            {
                return this._lNameField;
            }
            set
            {
                this._lNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRv1.IVisionService")]
    public interface IVisionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/Status", ReplyAction="http://tempuri.org/IVisionService/StatusResponse")]
        System.Threading.Tasks.Task<string> StatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/Login", ReplyAction="http://tempuri.org/IVisionService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string Uname, string Upass, int T);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/CreatePerson", ReplyAction="http://tempuri.org/IVisionService/CreatePersonResponse")]
        System.Threading.Tasks.Task CreatePersonAsync(string cid, string fName, string lName, string un, string pd, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/RemindersString", ReplyAction="http://tempuri.org/IVisionService/RemindersStringResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> RemindersStringAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/Reminders", ReplyAction="http://tempuri.org/IVisionService/RemindersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.Reminder>> RemindersAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/GetID", ReplyAction="http://tempuri.org/IVisionService/GetIDResponse")]
        System.Threading.Tasks.Task<int> GetIDAsync(string n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/EventsString", ReplyAction="http://tempuri.org/IVisionService/EventsStringResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> EventsStringAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/Events", ReplyAction="http://tempuri.org/IVisionService/EventsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.Event>> EventsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/NotesString", ReplyAction="http://tempuri.org/IVisionService/NotesStringResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> NotesStringAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/Notes", ReplyAction="http://tempuri.org/IVisionService/NotesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.NoteItem>> NotesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/CorpUsers", ReplyAction="http://tempuri.org/IVisionService/CorpUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.Person>> CorpUsersAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVisionService/CorpUsersString", ReplyAction="http://tempuri.org/IVisionService/CorpUsersStringResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> CorpUsersStringAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IVisionServiceChannel : SRv1.IVisionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class VisionServiceClient : System.ServiceModel.ClientBase<SRv1.IVisionService>, SRv1.IVisionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VisionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VisionServiceClient.GetBindingForEndpoint(endpointConfiguration), VisionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VisionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VisionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VisionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> StatusAsync()
        {
            return base.Channel.StatusAsync();
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string Uname, string Upass, int T)
        {
            return base.Channel.LoginAsync(Uname, Upass, T);
        }
        
        public System.Threading.Tasks.Task CreatePersonAsync(string cid, string fName, string lName, string un, string pd, int id)
        {
            return base.Channel.CreatePersonAsync(cid, fName, lName, un, pd, id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> RemindersStringAsync(int id)
        {
            return base.Channel.RemindersStringAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.Reminder>> RemindersAsync(int id)
        {
            return base.Channel.RemindersAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> GetIDAsync(string n)
        {
            return base.Channel.GetIDAsync(n);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> EventsStringAsync(int id)
        {
            return base.Channel.EventsStringAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.Event>> EventsAsync(int id)
        {
            return base.Channel.EventsAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> NotesStringAsync(int id)
        {
            return base.Channel.NotesStringAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.NoteItem>> NotesAsync(int id)
        {
            return base.Channel.NotesAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SRv1.Person>> CorpUsersAsync(int id)
        {
            return base.Channel.CorpUsersAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> CorpUsersStringAsync(int id)
        {
            return base.Channel.CorpUsersStringAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVisionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IVisionService))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVisionService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5000/VisionService/basichttp");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IVisionService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:5001/VisionService/WSHttps");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVisionService,
            
            WSHttpBinding_IVisionService,
        }
    }
}
